services:
  mongo:
    image: mongo:4.2.5
  myapp:
    build:
        dockerfile: Dockerfile
    env_file: .env
    environment:
      WAIT_HOSTS: mongo:27017
      DOCKER_DB: true
      MONGODB_URI: mongodb://mongo:27017/gameboxd
    ports:
      - '8080:8080'
    depends_on:
      - mongo